"""storylet branch tables

Revision ID: 12d5f0e95a10
Revises: 15eb7e2e075f
Create Date: 2022-11-16 20:16:33.184084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d5f0e95a10'
down_revision = '15eb7e2e075f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edit', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylet', schema=None) as batch_op:
        batch_op.drop_column('last_edit')

    # ### end Alembic commands ###
