"""storylet quality requirements

Revision ID: 370e65cbf875
Revises: 7eb4a3c139dc
Create Date: 2023-03-01 17:44:02.551172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370e65cbf875'
down_revision = '7eb4a3c139dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storylet_quality_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimum', sa.Integer(), nullable=True),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('quality_id', sa.Integer(), nullable=True),
    sa.Column('storylet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quality_id'], ['quality.id'], ),
    sa.ForeignKeyConstraint(['storylet_id'], ['storylet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storylet_quality_requirements')
    # ### end Alembic commands ###
