"""branch stuffs

Revision ID: 3e0ec4be0af5
Revises: 7d63deadc8c3
Create Date: 2022-11-29 17:59:45.203600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0ec4be0af5'
down_revision = '7d63deadc8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('action_cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_column('action_cost')
        batch_op.drop_column('order')

    # ### end Alembic commands ###
