"""hand table

Revision ID: 58e7f31149cb
Revises: 71fcef8161b3
Create Date: 2023-02-23 11:21:47.247691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e7f31149cb'
down_revision = '71fcef8161b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('storylet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['storylet_id'], ['storylet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand')
    # ### end Alembic commands ###
