"""storylet update 1

Revision ID: 7bccbfda0472
Revises: 12d5f0e95a10
Create Date: 2022-11-16 20:22:44.404854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bccbfda0472'
down_revision = '12d5f0e95a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylet', schema=None) as batch_op:
        batch_op.alter_column('available',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylet', schema=None) as batch_op:
        batch_op.alter_column('available',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
