"""fix available deck

Revision ID: bd7cac6d8d4d
Revises: 04873676af31
Create Date: 2022-11-17 18:28:28.310140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7cac6d8d4d'
down_revision = '04873676af31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck', sa.String(), nullable=True))
        batch_op.drop_column('available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storylet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('deck')

    # ### end Alembic commands ###
