"""hand slot

Revision ID: da67ada0cdec
Revises: 58e7f31149cb
Create Date: 2023-02-23 12:01:16.277116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da67ada0cdec'
down_revision = '58e7f31149cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand', schema=None) as batch_op:
        batch_op.drop_column('slot')

    # ### end Alembic commands ###
