"""user privilege

Revision ID: f3d4fb8dda12
Revises: 81c0eb14f981
Create Date: 2022-11-15 14:30:01.550661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d4fb8dda12'
down_revision = '81c0eb14f981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privilege_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('privilege_level')

    # ### end Alembic commands ###
